### ISSUE TITLE
我也没找到领取荧光棒的接口···

### ISSUE THREAD

**Issue by Curtion** [pyystone/douyu_gift#1]
我尝试了所有的XHR的接口都没有找到领取荧光棒的接口，我都怀疑需要WebSocket登陆认证服务器才会领取···

**Comment by pyystone** [comment]
他领取荧光棒 是隐藏在 查询礼物接口里面，然后内部逻辑有判断是否登录过某个直播间，应该是陈年逻辑，懒得去调整了

**Comment by Curtion** [comment]
> 他领取荧光棒是隐藏在查询礼物接口里面，然后内部逻辑有判断是否登录过某个直播间，应该是陈年逻辑，懒得去调整了

感谢，只能再试试按顺序请求了，如果失败那这个登陆判断可能是认证服务器来做的
