### ISSUE TITLE
感谢分享，17年暑假也写过相同的脚本遇到一点问题。

### ISSUE THREAD

**Issue by LunaticTian** [pyystone/douyu_gift#2]
送荧光棒这点解决，主要问题在于获取荧光棒上面，几个猜测获取荧光棒的接口都不是，可能在JS上？所以当时的解决方案是通过selenium访问直播间获取荧光棒，然后在送。这一点如果放在服务器上就很麻烦，不能使用chrome而是需要phantomJS，所以如果有更好的方法可以探讨一下。

**Comment by pyystone** [comment]
是这样的，通过chrome 只是一种比较省力的技巧，主要是可以节省很多API的访问，我也没有时间去研究。
想要纯服务器方案去做的话。
主要有2个方面需要考虑
1. 单纯cookie 上的需要考虑 token的过期问题。
2. 后荧光棒的获取上，大致猜测是没有API获取的（只能通过查询礼物接口获得荧光棒），目前的猜测逻辑是查询礼物的时候，会查询今天荧光棒是否已经发送，如果没有发送，会询问登陆服务器用户是否登陆过。
这样的逻辑的话，单纯进入直播间没有用，需要通过websocket（弹幕服务器里面的登陆API）去进行登陆，然后通过礼物查询接口应该就可以获得荧光棒了:-D
